# Generated by Django 5.0.1 on 2024-02-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('n_recetas', models.IntegerField()),
                ('dificultad', models.IntegerField()),
                ('porciones', models.IntegerField()),
                ('ingredientes', models.CharField(max_length=500)),
                ('procedimiento', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='C_receta',
        ),
        migrations.DeleteModel(
            name='V_recetas',
        ),
        migrations.RenameField(
            model_name='chef',
            old_name='profesion',
            new_name='especialidad',
        ),
    ]
