# Generated by Django 5.0.1 on 2024-02-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_recetas_delete_c_receta_delete_v_recetas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetas',
            name='nombre',
            field=models.CharField(default='comida', max_length=60),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='tipo',
            field=models.CharField(max_length=500),
        ),
    ]
