# Generated by Django 5.0.1 on 2024-02-13 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_recetas_nombre_alter_recetas_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recetas',
            name='n_recetas',
        ),
        migrations.RemoveField(
            model_name='recetas',
            name='tipo',
        ),
    ]
