# Generated by Django 5.0.1 on 2024-03-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_recetas_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='recetas_imagenes/'),
        ),
    ]
