# Generated by Django 5.0.1 on 2024-03-06 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0010_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.avatar'),
        ),
    ]
