# Generated by Django 5.0.1 on 2024-03-06 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0011_comentario_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='usuario',
            new_name='autor',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='avatar',
        ),
    ]
